### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/visualstudio-docs.fr-fr#17]
Should this rule and associated attribute be considered obsolete considering even dlls from .NET Core won't be CLS Compliant? https://github.com/aspnet/Home/issues/2689 . Considering it's "viral form" since all dependencies exposed on public api need to be CLS compliant too, it would relieve the library authors of the requests about supporting this.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 94e36897-6dc2-65f6-30c0-a53d054bd9fd
* Version Independent ID: 58289e5c-cb97-cdfb-58e5-3f4a315d047f
* Content: [CA1014 : Marquer les assemblys avec CLSCompliantAttribute](https://docs.microsoft.com/fr-ca/visualstudio/code-quality/ca1014-mark-assemblies-with-clscompliantattribute)
* Content Source: [docs/code-quality/ca1014-mark-assemblies-with-clscompliantattribute.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/code-quality/ca1014-mark-assemblies-with-clscompliantattribute.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1417](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1417) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Thieum, 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/1417. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
