### ISSUE TITLE
Ne fonctionne plus avec l'option Runtime Stack Node.js 8.9 ci dessus

### ISSUE THREAD

**Issue by ynguyenluat** [MicrosoftDocs/visualstudio-docs.fr-fr#71]
Correction: ajouter le paramètre d'application WEBSITE_NODE_DEFAULT_VERSION=8.9.0

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 52d4b59f-07fd-b894-01f7-9bc2fc06e98a
* Version Independent ID: 1cb6913e-21a7-48d2-8b83-cb416304b0c5
* Content: [Publier une application Node.js sur App Service Linux - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2019#feedback)
* Content Source: [docs/javascript/publish-nodejs-app-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/javascript/publish-nodejs-app-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @ynguyenluat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ynguyenluat

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4293

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
