### ISSUE TITLE
Rule CA1710: Add configurability section - Exclude indirect base types

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs.fr-fr#77]
Rule CA1710 was updated to allow for a new configurability section. This restrict the analysis to the current base type.

Note that on another PR we updated the default value to be `true`.

See https://github.com/dotnet/roslyn-analyzers/pull/3148/files#diff-1b5cdc4937a8cdfc79545945ad6c0783R413-R438 and see also https://github.com/dotnet/roslyn-analyzers/pull/3236

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 83202117-8bd8-aa22-d55c-42ecc59fc11f
* Version Independent ID: 2374ea4f-0f8d-283e-5803-7c8de04b48f7
* Content: [CA1710 : Les identificateurs doivent être dotés d'un suffixe correct - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/code-quality/ca1710?view=vs-2019#configurability)
* Content Source: [docs/code-quality/ca1710.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/code-quality/ca1710.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @Evangelink
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Evangelink, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5234. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
